service: mat-service

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  api-name: hn-mat-service-api
  stage: ${opt:stage, env:SLS_STAGE, 'dev'}
  dbname: matServiceDb

plugins:
  - serverless-offline-ssm
  - serverless-offline

functions:
  hn-mat-service:
    name: ${self:service}-${self:provider.stage}
    handler: src/lambda.handler
    events:
      - http:
          path: api/{proxy+}
          method: ANY
      - http: ANY /
      - http: ANY /{proxy+}

mat-service-single-view-api-authorizer:
  name: mat-service-single-view-api-authorizer-${self:provider.stage}
  role: ${self:custom.lambdaRole.${self:provider.stage}}
  handler: authorizer.handler
  package:
    include:
      - authorizer.js
      - node_modules/**
  environment:
    jwtsecret: ${ssm:/common/hackney-jwt-secret}
    allowedGroups:
      'Fn::Join':
        - ','
        - ${self:custom.allowedGroups.${self:provider.stage}}
    ENV: ${self:provider.stage}

resources:
  Resources:
    matServiceDbSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Access to Postgres
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: '5432'
            ToPort: '5432'
            CidrIp: 0.0.0.0/0

    matServiceDb:
      Type: 'AWS::RDS::DBInstance'
      Properties:
        DBInstanceIdentifier: 'mat-service-db-${self:provider.stage}'
        DBName: ${self:provider.dbname}
        AllocatedStorage: 5
        DBInstanceClass: 'db.t2.micro'
        Engine: 'postgres'
        EngineVersion: '11.7'
        MasterUsername: ${ssm:/${self:provider.stage}-mat-service-db-MASTER_USERNAME}
        MasterUserPassword: ${ssm:/${self:provider.stage}-mat-service-db-MASTER_PASSWORD~true}
        VPCSecurityGroups:
          - Fn::GetAtt:
              - matServiceDbSecurityGroup
              - GroupId
      DeletionPolicy: 'Snapshot'

custom:
  stage: ${self:provider.stage}
  lambdaRole:
    staging: arn:aws:iam::492942404536:role/mat-service-staging-eu-west-2-lambdaRole
    production: arn:aws:iam::492942404536:role/mat-service-production-eu-west-2-lambdaRole

  allowedGroups:
    staging:
      - contact-centre-staging
      - benefit-counter-staging
      - housing-counter-staging
      - housing-officer-staging
      - area-housing-manager-staging
      - housing-needs-staging
    production:
      - contact-centre-production
      - benefit-counter-production
      - housing-counter-production
      - housing-officer-production
      - area-housing-manager-production
      - housing-needs-production
