service: mat-service

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  api-name: hn-mat-service-api
  stage: dev
  dbname: matServiceDb
  environment:
    DB_USER: ${ssm:/${self:custom.stage}-mat-service-db-MASTER_USERNAME}
    DB_PW: ${ssm:/${self:custom.stage}-mat-service-db-MASTER_PASSWORD~true}

plugins:
  - serverless-offline-ssm
  - serverless-offline

functions:
  hn-mat-service:
    name: ${self:service}-${self:custom.stage}
    handler: src/lambda.handler
    events:
      - http:
          path: api/{proxy+}
          method: ANY
      - http: ANY /
      - http: ANY /{proxy+}

mat-service-api-authorizer:
  name: mat-service-api-authorizer-${self:custom.stage}
  role: ${self:custom.lambdaRole.${self:custom.stage}}
  handler: authorizer.handler
  package:
    include:
      - authorizer.js
      - node_modules/**
  environment:
    jwtsecret: ${ssm:/common/hackney-jwt-secret~true}
    allowedGroups:
      'Fn::Join':
        - ','
        - ${self:custom.allowedGroups.${self:custom.stage}}
    ENV: ${self:custom.stage}

resources:
  Resources:
    matServiceDbSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Access to Postgres
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: '5432'
            ToPort: '5432'
            CidrIp: 0.0.0.0/0
    matServiceDb:
      Type: 'AWS::RDS::DBInstance'
      Properties:
        DBInstanceIdentifier: 'mat-service-db-${self:custom.stage}'
        DBName: ${self:provider.dbname}
        AllocatedStorage: 5
        DBInstanceClass: 'db.t2.micro'
        Engine: 'postgres'
        EngineVersion: '11.7'
        MasterUsername: "DB_USER"
        MasterUserPassword: "DB_PW"
        VPCSecurityGroups:
          - Fn::GetAtt:
              - matServiceDbSecurityGroup
              - GroupId
      DeletionPolicy: 'Snapshot'

custom:
  stage: ${opt:stage, self:provider.stage}
  lambdaRole:
    staging: arn:aws:iam::492942404536:role/mat-service-staging-eu-west-2-lambdaRole
    production: arn:aws:iam::492942404536:role/mat-service-production-eu-west-2-lambdaRole
  allowedGroups:
    staging:
      - contact-centre-staging
      - benefit-counter-staging
      - housing-counter-staging
      - housing-officer-staging
      - area-housing-manager-staging
      - housing-needs-staging
    production:
      - contact-centre-production
      - benefit-counter-production
      - housing-counter-production
      - housing-officer-production
      - area-housing-manager-production
      - housing-needs-production
  serverless-offline-ssm:
    stages:
      - dev
      