service: serverless-test

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  stage: dev 

functions:
  hello:
    handler: pages/index.handler
    events:
      - http:
          path: hello
          method: get
