version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.0.0
  aws_assume_role: lbh-hackit/aws_assume_role@0.1.0

executors:
  build-executor:
    docker:
      - image: circleci/node:12.13
    #working_directory: ~/repo
 
jobs:
  build-deploy-dev:
    executor: build-executor  

    steps:
      # - aws_assume_role/assume_role:
      #     account: $AWS_ACCOUNT
      #     profile_name: default
      #     role: 'LBH_Circle_CI_Deployment_Role'
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION

      - run:
          name: deploy
          command: |
            ls -al
            sudo npm i -g serverless && sls deploy
            
workflows:
  version: 2

  continuous-delivery:
    jobs:
      - build-deploy-dev:
          filters:
            branches:
              only:
                - test/serverless-deployment
